# Generated by Django 5.2.5 on 2025-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_policy_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnercompany",
            name="logo",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
