# Generated by Django 5.2.5 on 2025-09-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_partnercompany_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Enter the AA text", null=True
                    ),
                ),
            ],
        ),
    ]
