# Generated by Django 5.2.5 on 2025-09-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_partner_link_remove_partner_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True, help_text="Enter the name text", null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="partner",
            name="text",
        ),
        migrations.AddField(
            model_name="partner",
            name="name",
            field=models.TextField(
                blank=True, help_text="Enter the name text", null=True
            ),
        ),
    ]
