# Generated by Django 5.2.5 on 2025-09-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_pard_remove_partner_text_partner_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="link",
            field=models.URLField(
                blank=True, help_text="Enter the link url", null=True
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="logo",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
