# Generated by Django 5.2.5 on 2025-09-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_aa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AA",
        ),
    ]
