# Generated by Django 5.2.5 on 2025-09-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="text",
            field=models.TextField(
                blank=True, help_text="Enter the policy text", null=True
            ),
        ),
    ]
