# Generated by Django 5.2.5 on 2025-09-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_partner_link_partner_logo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pard",
        ),
    ]
